In [1]:
# ============================================
# STEP 1: SECURITY KNOWLEDGE BASE
# ============================================

security_knowledge = [
    {
        "category": "Coding Standard",
        "title": "Meaningful Variable Names",
        "content": "Use clear and meaningful variable names. Avoid names such as x, y, temp or data when they do not describe the purpose of the variable.",
        "keywords": ["variable", "naming", "readability", "maintainability"]
    },

    {
        "category": "Coding Standard",
        "title": "Functions Should Have Single Responsibility",
        "content": "A function should perform one clear task. Large functions with multiple responsibilities are difficult to test, maintain and debug.",
        "keywords": ["function", "single responsibility", "maintainability"]
    },

    {
        "category": "Coding Standard",
        "title": "Avoid Hardcoded Credentials",
        "content": "Passwords, API keys, tokens and other secrets should not be directly written inside source code. Use environment variables or a secure secret manager.",
        "keywords": ["password", "api key", "token", "secret", "credential"]
    },

    {
        "category": "Common Bug",
        "title": "Division by Zero",
        "content": "Always validate the denominator before performing division. Division by zero can cause runtime errors.",
        "keywords": ["division", "zero", "runtime error", "exception"]
    },

    {
        "category": "Common Bug",
        "title": "Null or None Value",
        "content": "Check whether an object or variable is null or None before accessing its properties or methods.",
        "keywords": ["null", "none", "object", "runtime error"]
    },

    {
        "category": "Common Bug",
        "title": "Array Index Out of Bounds",
        "content": "Make sure array indexes are within the valid range before accessing an element.",
        "keywords": ["array", "index", "bounds", "list"]
    },

    {
        "category": "Common Bug",
        "title": "Unhandled Exceptions",
        "content": "Applications should handle expected exceptions properly instead of allowing unexpected crashes.",
        "keywords": ["exception", "error handling", "crash"]
    },

    {
        "category": "Secure Coding",
        "title": "SQL Injection Prevention",
        "content": "Never construct SQL queries by directly concatenating untrusted user input. Use parameterized queries or prepared statements.",
        "keywords": ["sql", "injection", "database", "query", "user input"]
    },

    {
        "category": "Secure Coding",
        "title": "Input Validation",
        "content": "Validate and sanitize user-controlled input before processing it. Check type, length, format and allowed values.",
        "keywords": ["input", "validation", "sanitization", "user input"]
    },

    {
        "category": "Secure Coding",
        "title": "Command Injection Prevention",
        "content": "Avoid passing untrusted input directly to operating system commands. Prefer safe APIs and validate allowed input.",
        "keywords": ["command", "os", "shell", "injection"]
    },

    {
        "category": "Secure Coding",
        "title": "Path Traversal Prevention",
        "content": "Do not directly use user-controlled file paths. Validate paths and restrict file access to approved directories.",
        "keywords": ["path", "file", "directory", "traversal"]
    },

    {
        "category": "Secure Coding",
        "title": "Password Storage",
        "content": "Passwords should never be stored as plain text. Use a strong password hashing algorithm with appropriate salt.",
        "keywords": ["password", "hash", "authentication", "storage"]
    },

    {
        "category": "Secure Coding",
        "title": "Sensitive Information in Logs",
        "content": "Do not log passwords, authentication tokens, API keys or other sensitive information.",
        "keywords": ["logging", "password", "token", "api key", "sensitive"]
    },

    {
        "category": "Secure Coding",
        "title": "Least Privilege",
        "content": "Give users, applications and services only the permissions required to perform their tasks.",
        "keywords": ["permission", "authorization", "privilege", "access control"]
    }
]

print("Knowledge base created successfully!")
print("Total entries:", len(security_knowledge))

Knowledge base created successfully!
Total entries: 14

In [2]:
# ============================================
# STEP 2: PREPARE DOCUMENTS FOR RETRIEVAL
# ============================================

documents = []

for item in security_knowledge:
    text = (
        item["category"] + " " +
        item["title"] + " " +
        item["content"] + " " +
        " ".join(item["keywords"])
    )

    documents.append(text)

print("Documents prepared:", len(documents))

Documents prepared: 14

In [3]:
# ============================================
# STEP 3: CREATE RETRIEVAL SYSTEM
# ============================================

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

vectorizer = TfidfVectorizer(
    lowercase=True,
    stop_words="english"
)

knowledge_vectors = vectorizer.fit_transform(documents)

print("TF-IDF knowledge index created!")
print("Vector shape:", knowledge_vectors.shape)

TF-IDF knowledge index created!
Vector shape: (14, 156)

In [4]:
# ============================================
# STEP 4: RETRIEVE RELEVANT KNOWLEDGE
# ============================================

def retrieve_knowledge(query, top_k=3):

    query_vector = vectorizer.transform([query])

    similarity_scores = cosine_similarity(
        query_vector,
        knowledge_vectors
    )[0]

    ranked_indexes = similarity_scores.argsort()[::-1]

    results = []

    for index in ranked_indexes[:top_k]:

        results.append({
            "category": security_knowledge[index]["category"],
            "title": security_knowledge[index]["title"],
            "content": security_knowledge[index]["content"],
            "score": float(similarity_scores[index])
        })

    return results

In [5]:
results = retrieve_knowledge(
    "password hardcoded inside Python source code",
    top_k=3
)

for result in results:
    print("=" * 60)
    print("Category:", result["category"])
    print("Title:", result["title"])
    print("Score:", round(result["score"], 3))
    print("Knowledge:", result["content"])

============================================================
Category: Coding Standard
Title: Avoid Hardcoded Credentials
Score: 0.431
Knowledge: Passwords, API keys, tokens and other secrets should not be directly written inside source code. Use environment variables or a secure secret manager.
============================================================
Category: Secure Coding
Title: Password Storage
Score: 0.183
Knowledge: Passwords should never be stored as plain text. Use a strong password hashing algorithm with appropriate salt.
============================================================
Category: Secure Coding
Title: Sensitive Information in Logs
Score: 0.056
Knowledge: Do not log passwords, authentication tokens, API keys or other sensitive information.

In [6]:
results = retrieve_knowledge(
    "SQL query directly uses user input",
    top_k=3
)

for result in results:
    print("=" * 60)
    print("Category:", result["category"])
    print("Title:", result["title"])
    print("Score:", round(result["score"], 3))
    print("Knowledge:", result["content"])

============================================================
Category: Secure Coding
Title: SQL Injection Prevention
Score: 0.649
Knowledge: Never construct SQL queries by directly concatenating untrusted user input. Use parameterized queries or prepared statements.
============================================================
Category: Secure Coding
Title: Input Validation
Score: 0.364
Knowledge: Validate and sanitize user-controlled input before processing it. Check type, length, format and allowed values.
============================================================
Category: Secure Coding
Title: Command Injection Prevention
Score: 0.188
Knowledge: Avoid passing untrusted input directly to operating system commands. Prefer safe APIs and validate allowed input.

In [7]:
password = "admin123"

In [8]:
code_issue = "hardcoded password found in source code"

results = retrieve_knowledge(code_issue, top_k=3)

print("SECURITY KNOWLEDGE")
print("=" * 60)

for result in results:
    print(f"[{result['category']}] {result['title']}")
    print(result["content"])
    print()

SECURITY KNOWLEDGE
============================================================
[Coding Standard] Avoid Hardcoded Credentials
Passwords, API keys, tokens and other secrets should not be directly written inside source code. Use environment variables or a secure secret manager.

[Secure Coding] Password Storage
Passwords should never be stored as plain text. Use a strong password hashing algorithm with appropriate salt.

[Secure Coding] Sensitive Information in Logs
Do not log passwords, authentication tokens, API keys or other sensitive information.

In [9]:
# ============================================
# STEP 7: SECURITY GUIDANCE FUNCTION
# ============================================

def get_security_guidance(issue, top_k=3):

    results = retrieve_knowledge(issue, top_k)

    guidance = []

    for result in results:
        guidance.append({
            "category": result["category"],
            "title": result["title"],
            "recommendation": result["content"],
            "similarity": round(result["score"], 3)
        })

    return guidance


# Test the function
issue = "hardcoded password found in source code"

guidance = get_security_guidance(issue, top_k=3)

print("SECURITY GUIDANCE")
print("=" * 60)

for item in guidance:
    print("Category:", item["category"])
    print("Issue:", item["title"])
    print("Recommendation:", item["recommendation"])
    print("Similarity:", item["similarity"])
    print("-" * 60)

SECURITY GUIDANCE
============================================================
Category: Coding Standard
Issue: Avoid Hardcoded Credentials
Recommendation: Passwords, API keys, tokens and other secrets should not be directly written inside source code. Use environment variables or a secure secret manager.
Similarity: 0.381
------------------------------------------------------------
Category: Secure Coding
Issue: Password Storage
Recommendation: Passwords should never be stored as plain text. Use a strong password hashing algorithm with appropriate salt.
Similarity: 0.207
------------------------------------------------------------
Category: Secure Coding
Issue: Sensitive Information in Logs
Recommendation: Do not log passwords, authentication tokens, API keys or other sensitive information.
Similarity: 0.063
------------------------------------------------------------

In [10]:
# ============================================
# STEP 8: COMBINE ISSUE + RETRIEVED KNOWLEDGE
# ============================================

def analyze_security_issue(issue, severity="MEDIUM"):

    guidance = get_security_guidance(issue, top_k=3)

    analysis = {
        "issue": issue,
        "severity": severity,
        "recommendations": guidance
    }

    return analysis


# Test
result = analyze_security_issue(
    "hardcoded password found in source code",
    severity="HIGH"
)

print("SECURITY ANALYSIS")
print("=" * 60)

print("Issue:", result["issue"])
print("Severity:", result["severity"])

print("\nRelevant Knowledge:")

for item in result["recommendations"]:
    print("\nCategory:", item["category"])
    print("Rule:", item["title"])
    print("Recommendation:", item["recommendation"])
    print("Similarity:", item["similarity"])

SECURITY ANALYSIS
============================================================
Issue: hardcoded password found in source code
Severity: HIGH

Relevant Knowledge:

Category: Coding Standard
Rule: Avoid Hardcoded Credentials
Recommendation: Passwords, API keys, tokens and other secrets should not be directly written inside source code. Use environment variables or a secure secret manager.
Similarity: 0.381

Category: Secure Coding
Rule: Password Storage
Recommendation: Passwords should never be stored as plain text. Use a strong password hashing algorithm with appropriate salt.
Similarity: 0.207

Category: Secure Coding
Rule: Sensitive Information in Logs
Recommendation: Do not log passwords, authentication tokens, API keys or other sensitive information.
Similarity: 0.063

In [11]:
# ============================================
# STEP 9: CREATE FINAL RISK REPORT
# ============================================

import pandas as pd

# Example security findings
security_findings = [
    {
        "file": "sample.py",
        "line": 26,
        "issue": "Hardcoded password found in source code",
        "severity": "HIGH"
    },
    {
        "file": "sample.py",
        "line": 10,
        "issue": "Potential security issue detected",
        "severity": "MEDIUM"
    }
]

report_rows = []

for finding in security_findings:

    guidance = get_security_guidance(
        finding["issue"],
        top_k=3
    )

    # Get the most relevant recommendation
    if guidance:
        best = guidance[0]

        recommendation = best["recommendation"]
        rule = best["title"]
        similarity = best["similarity"]
    else:
        recommendation = "No security guidance found."
        rule = "N/A"
        similarity = 0

    report_rows.append({
        "File": finding["file"],
        "Line": finding["line"],
        "Issue": finding["issue"],
        "Severity": finding["severity"],
        "Security Rule": rule,
        "Recommendation": recommendation,
        "Similarity": similarity
    })


# Create DataFrame
final_report = pd.DataFrame(report_rows)

print("FINAL RISK REPORT")
print("=" * 80)

display(final_report)

FINAL RISK REPORT
================================================================================

,File,Line,Issue,Severity,Security Rule,Recommendation,Similarity
0,sample.py,26,Hardcoded password found in source code,HIGH,Avoid Hardcoded Credentials,"Passwords, API keys, tokens and other secrets ...",0.381
1,sample.py,10,Potential security issue detected,MEDIUM,Least Privilege,"Give users, applications and services only the...",0.000

In [12]:
# ============================================
# STEP 9B: SAVE FINAL REPORT AS CSV
# ============================================

output_file = "final_risk_report.csv"

final_report.to_csv(
    output_file,
    index=False
)

print("CSV created successfully!")
print("File:", output_file)

CSV created successfully!
File: final_risk_report.csv

In [13]:
import os

print("File exists:", os.path.exists("final_risk_report.csv"))

if os.path.exists("final_risk_report.csv"):
    print("File size:", os.path.getsize("final_risk_report.csv"), "bytes")

File exists: True
File size: 478 bytes

In [15]:
# ============================================
# STEP 10: VIEW FINAL CSV
# ============================================

import pandas as pd

df = pd.read_csv("final_risk_report.csv")

print("Rows:", len(df))
print("Columns:", list(df.columns))

display(df)

Rows: 2
Columns: ['File', 'Line', 'Issue', 'Severity', 'Security Rule', 'Recommendation', 'Similarity']

,File,Line,Issue,Severity,Security Rule,Recommendation,Similarity
0,sample.py,26,Hardcoded password found in source code,HIGH,Avoid Hardcoded Credentials,"Passwords, API keys, tokens and other secrets ...",0.381
1,sample.py,10,Potential security issue detected,MEDIUM,Least Privilege,"Give users, applications and services only the...",0.000

In [16]:
# ============================================
# DOWNLOAD FINAL REPORT
# ============================================

from google.colab import files

files.download("final_risk_report.csv")

In [17]:
import os

print("Current directory:")
print(os.getcwd())

print("\nPython files:")
for file in os.listdir():
    if file.endswith(".py"):
        print("-", file)

Current directory:
/content

Python files:

In [14]:
security_findings = [...]

In [19]:
from google.colab import files

uploaded = files.upload()

Saving sample.py to sample.py

In [20]:
import os

print("Uploaded files:")

for file in os.listdir():
    print("-", file)

Uploaded files:
- .config
- final_risk_report.csv
- sample.py
- sample_data

In [23]:
!cat sample.py

In [24]:
!pip install -q bandit radon

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.7/134.7 kB 3.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.8/52.8 kB 2.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.9/54.9 kB 2.4 MB/s eta 0:00:00

In [25]:
# ============================================
# STEP 12: CREATE TEST SOURCE FILE
# ============================================

sample_code = '''
import subprocess

password = "admin123"

def login(username, user_password):
    if user_password == password:
        return True
    return False

def run_command(user_input):
    subprocess.call(user_input, shell=True)

print("Login system started")
'''

with open("sample.py", "w") as f:
    f.write(sample_code)

print("sample.py created successfully!")

sample.py created successfully!

In [26]:
!cat sample.py

import subprocess

password = "admin123"

def login(username, user_password):
    if user_password == password:
        return True
    return False

def run_command(user_input):
    subprocess.call(user_input, shell=True)

print("Login system started")

In [27]:
!bandit -r sample.py -f json -o bandit_report.json

[main]	INFO	profile include tests: None
[main]	INFO	profile exclude tests: None
[main]	INFO	cli include tests: None
[main]	INFO	cli exclude tests: None
[json]	INFO	JSON output written to file: bandit_report.json

In [28]:
import json

with open("bandit_report.json", "r") as f:
    bandit_data = json.load(f)

print("Bandit findings:", len(bandit_data["results"]))

Bandit findings: 3

In [29]:
print("Bandit findings:", len(bandit_data["results"]))

Bandit findings: 3

In [30]:
# ============================================
# STEP 14: EXTRACT BANDIT FINDINGS
# ============================================

findings = []

for result in bandit_data["results"]:

    finding = {
        "file": result.get("filename", "Unknown"),
        "line": result.get("line_number", 0),
        "issue": result.get("issue_text", "Unknown security issue"),
        "severity": result.get("issue_severity", "UNKNOWN"),
        "confidence": result.get("issue_confidence", "UNKNOWN"),
        "test_id": result.get("test_id", "UNKNOWN")
    }

    findings.append(finding)

print("Extracted findings:", len(findings))

for finding in findings:
    print("=" * 60)
    print("File:", finding["file"])
    print("Line:", finding["line"])
    print("Issue:", finding["issue"])
    print("Severity:", finding["severity"])
    print("Confidence:", finding["confidence"])
    print("Test ID:", finding["test_id"])

Extracted findings: 3
============================================================
File: ./sample.py
Line: 2
Issue: Consider possible security implications associated with the subprocess module.
Severity: LOW
Confidence: HIGH
Test ID: B404
============================================================
File: ./sample.py
Line: 4
Issue: Possible hardcoded password: 'admin123'
Severity: LOW
Confidence: MEDIUM
Test ID: B105
============================================================
File: ./sample.py
Line: 12
Issue: subprocess call with shell=True identified, security issue.
Severity: HIGH
Confidence: HIGH
Test ID: B602

In [31]:
# ============================================
# STEP 15: CONNECT BANDIT TO KNOWLEDGE BASE
# ============================================

bandit_guidance = []

for finding in findings:

    guidance = get_security_guidance(
        finding["issue"],
        top_k=3
    )

    best = guidance[0] if guidance else None

    bandit_guidance.append({
        "File": finding["file"],
        "Line": finding["line"],
        "Issue": finding["issue"],
        "Severity": finding["severity"],
        "Confidence": finding["confidence"],
        "Test_ID": finding["test_id"],
        "Security_Rule": best["title"] if best else "No matching rule",
        "Recommendation": best["recommendation"] if best else "No recommendation found",
        "Similarity": best["similarity"] if best else 0
    })

print("Bandit findings connected to knowledge base!")

Bandit findings connected to knowledge base!

In [32]:
import pandas as pd

bandit_report = pd.DataFrame(bandit_guidance)

display(bandit_report)

,File,Line,Issue,Severity,Confidence,Test_ID,Security_Rule,Recommendation,Similarity
0,./sample.py,2,Consider possible security implications associ...,LOW,HIGH,B404,Least Privilege,"Give users, applications and services only the...",0.000
1,./sample.py,4,Possible hardcoded password: 'admin123',LOW,MEDIUM,B105,Password Storage,Passwords should never be stored as plain text...,0.311
2,./sample.py,12,"subprocess call with shell=True identified, se...",HIGH,HIGH,B602,Command Injection Prevention,Avoid passing untrusted input directly to oper...,0.216

In [33]:
# ============================================
# STEP 16: RADON COMPLEXITY ANALYSIS
# ============================================

import subprocess
import json

radon_result = subprocess.run(
    ["radon", "cc", "sample.py", "-j"],
    capture_output=True,
    text=True
)

print("Radon output:")
print(radon_result.stdout)

Radon output:
{"sample.py": [{"type": "function", "rank": "A", "complexity": 2, "col_offset": 0, "endline": 9, "lineno": 6, "name": "login", "closures": []}, {"type": "function", "rank": "A", "complexity": 1, "col_offset": 0, "endline": 12, "lineno": 11, "name": "run_command", "closures": []}]}

In [34]:
# ============================================
# STEP 16B: READ RADON RESULTS
# ============================================

radon_data = json.loads(radon_result.stdout)

print("RADON RESULTS")
print("=" * 60)

for filename, functions in radon_data.items():

    for function in functions:

        print("Function:", function["name"])
        print("Complexity:", function["complexity"])
        print("Rank:", function["rank"])
        print("Line:", function["lineno"])
        print("-" * 60)

RADON RESULTS
============================================================
Function: login
Complexity: 2
Rank: A
Line: 6
------------------------------------------------------------
Function: run_command
Complexity: 1
Rank: A
Line: 11
------------------------------------------------------------

In [35]:
# ============================================
# STEP 17: CALCULATE RISK SCORE
# ============================================

severity_points = {
    "LOW": 1,
    "MEDIUM": 5,
    "HIGH": 10
}

total_security_points = 0

for finding in findings:
    severity = finding["severity"].upper()
    total_security_points += severity_points.get(severity, 0)

# Calculate average complexity
complexities = []

for filename, functions in radon_data.items():
    for function in functions:
        complexities.append(function["complexity"])

if complexities:
    average_complexity = sum(complexities) / len(complexities)
else:
    average_complexity = 0

# Complexity contribution
if average_complexity <= 5:
    complexity_points = 0
elif average_complexity <= 10:
    complexity_points = 5
else:
    complexity_points = 10

# Final score
risk_score = total_security_points + complexity_points

# Keep score between 0 and 100
risk_score = min(risk_score, 100)

# Risk category
if risk_score >= 20:
    risk_level = "HIGH"
elif risk_score >= 10:
    risk_level = "MEDIUM"
else:
    risk_level = "LOW"

print("RISK ANALYSIS")
print("=" * 60)
print("Security points:", total_security_points)
print("Average complexity:", round(average_complexity, 2))
print("Complexity points:", complexity_points)
print("Final risk score:", risk_score)
print("Risk level:", risk_level)

RISK ANALYSIS
============================================================
Security points: 12
Average complexity: 1.5
Complexity points: 0
Final risk score: 12
Risk level: MEDIUM

In [36]:
# ============================================
# STEP 18: GENERATE FINAL RISK REPORT
# ============================================

final_rows = []

for finding in findings:

    guidance = get_security_guidance(
        finding["issue"],
        top_k=3
    )

    best = guidance[0] if guidance else None

    final_rows.append({
        "File": finding["file"],
        "Line": finding["line"],
        "Issue": finding["issue"],
        "Severity": finding["severity"],
        "Confidence": finding["confidence"],
        "Test_ID": finding["test_id"],
        "Security_Rule": best["title"] if best else "No matching rule",
        "Recommendation": best["recommendation"] if best else "No recommendation found",
        "Similarity": best["similarity"] if best else 0,
        "Average_Complexity": round(average_complexity, 2),
        "Risk_Score": risk_score,
        "Risk_Level": risk_level
    })

final_report = pd.DataFrame(final_rows)

display(final_report)

,File,Line,Issue,Severity,Confidence,Test_ID,Security_Rule,Recommendation,Similarity,Average_Complexity,Risk_Score,Risk_Level
0,./sample.py,2,Consider possible security implications associ...,LOW,HIGH,B404,Least Privilege,"Give users, applications and services only the...",0.000,1.5,12,MEDIUM
1,./sample.py,4,Possible hardcoded password: 'admin123',LOW,MEDIUM,B105,Password Storage,Passwords should never be stored as plain text...,0.311,1.5,12,MEDIUM
2,./sample.py,12,"subprocess call with shell=True identified, se...",HIGH,HIGH,B602,Command Injection Prevention,Avoid passing untrusted input directly to oper...,0.216,1.5,12,MEDIUM

In [37]:
# ============================================
# STEP 19: SAVE FINAL CSV
# ============================================

final_report.to_csv(
    "final_risk_report.csv",
    index=False
)

print("============================================")
print("FINAL REPORT CREATED SUCCESSFULLY")
print("============================================")
print("File: final_risk_report.csv")
print("Rows:", len(final_report))
print("Risk Score:", risk_score)
print("Risk Level:", risk_level)

============================================
FINAL REPORT CREATED SUCCESSFULLY
============================================
File: final_risk_report.csv
Rows: 3
Risk Score: 12
Risk Level: MEDIUM

In [38]:
import os

print("File exists:", os.path.exists("final_risk_report.csv"))
print("File size:", os.path.getsize("final_risk_report.csv"), "bytes")

File exists: True
File size: 833 bytes

In [39]:
# ============================================
# STEP 20: VERIFY FINAL REPORT
# ============================================

import pandas as pd

final_report = pd.read_csv("final_risk_report.csv")

print("FINAL RISK REPORT")
print("=" * 80)

print("Number of findings:", len(final_report))
print("Columns:", len(final_report.columns))

display(final_report)

print("\nRisk Score:", final_report["Risk_Score"].iloc[0])
print("Risk Level:", final_report["Risk_Level"].iloc[0])

FINAL RISK REPORT
================================================================================
Number of findings: 3
Columns: 12

,File,Line,Issue,Severity,Confidence,Test_ID,Security_Rule,Recommendation,Similarity,Average_Complexity,Risk_Score,Risk_Level
0,./sample.py,2,Consider possible security implications associ...,LOW,HIGH,B404,Least Privilege,"Give users, applications and services only the...",0.000,1.5,12,MEDIUM
1,./sample.py,4,Possible hardcoded password: 'admin123',LOW,MEDIUM,B105,Password Storage,Passwords should never be stored as plain text...,0.311,1.5,12,MEDIUM
2,./sample.py,12,"subprocess call with shell=True identified, se...",HIGH,HIGH,B602,Command Injection Prevention,Avoid passing untrusted input directly to oper...,0.216,1.5,12,MEDIUM

Risk Score: 12
Risk Level: MEDIUM

In [40]:
from google.colab import files

files.download("final_risk_report.csv")